import type { Metadata } from "next";
import { Lato, Nixie_One } from "next/font/google";
import clsx from "clsx";

import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
  weight: ["300", "400", "700", "900"],
});

const nixieOne = Nixie_One({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nixie-one",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={clsx(lato.variable, nixieOne.variable, "scroll-smooth")}
    >
      <body className="font-sans text-base/snug text-gray-900 antialiased">
        {children}
      </body>
    </html>
  );
}
